# Intended to be used with docker-compose file in the studio or stackn repository.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: studio-event-listener
  name: studio-event-listener
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: studio-event-listener
  template:
    metadata:
      labels:
        name: studio-event-listener
        app: stackn-studio
        allow-api-access: "true"
    spec:
      containers:
      - image: ghcr.io/scaleoutsystems/studio-kube-controller:feature-sk-486
        imagePullPolicy: Always
        name: studio-event-listener
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 20Mi
        env:
        - name: EVENT_LISTENER_USERNAME
          value: "<username-set-in-docker-compose-file>"
        - name: EVENT_LISTENER_PASSWORD
          value: "<password-set-in-docker-compose-file>"
        - name: STUDIO_SERVICE_NAME
          value: "<host-machine-ip>"
        - name: STUDIO_SERVICE_PORT
          value: "8080"
        - name: APP_STATUS_ENDPOINT
          value: "api/app/status"
        - name: TOKEN_ENDPOINT
          value: "api/token-auth/"
      restartPolicy: Always