apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: studio-event-listener
  name: studio-event-listener
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: studio-event-listener
  template:
    metadata:
      labels:
        name: studio-event-listener
        app: stackn-studio
        allow-api-access: "true"
    spec:
      automountServiceAccountToken: true
      serviceAccountName: studio
      containers:
      # - image: k3d-registry:35187/studio-event:latest
      - image: localhost:32000/event-listener:latest
        imagePullPolicy: Always
        name: studio-event-listener
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 20Mi
        env:
        - name: EVENT_LISTENER_USERNAME
          value: "event_listener_user"
        - name: EVENT_LISTENER_PASSWORD
          value: "xDJd6G6cAp"
        - name: STUDIO_SERVICE_NAME
          value: "studio-studio"
        - name: STUDIO_SERVICE_PORT
          value: "8080"
        - name: APP_STATUS_ENDPOINT
          value: "api/app/status"
        - name: TOKEN_ENDPOINT
          value: "api/token-auth/"
      restartPolicy: Always